# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/code_tokenizers',
                'doc_host': 'https://ncoop57.github.io',
                'git_url': 'https://github.com/ncoop57/code_tokenizers',
                'lib_path': 'code_tokenizers'},
  'syms': {'code_tokenizers.core': {'code_tokenizers.core.foo': ('core.html#foo', 'code_tokenizers/core.py')}}}