# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/01_cli.ipynb 2
import code_tokenizers
import os
import shutil
import urllib.request

from fastcore.script import *
from pathlib import Path
from tree_sitter import Language
